
BIN=array constructor

all: $(BIN)

clean:
	rm $(BIN)

# g++ in ubuntu 18.04 default to g++14, woo !

array: array.cpp
	g++ array.cpp -o array

constructor: constructor.cpp
	g++ constructor.cpp -o constructor
